version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "puppeteer"
      - dependency-name: "reactstrap"
  - package-ecosystem: "npm"
    directory: "/express-server"
    schedule:
      interval: "daily"
