version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "puppeteer"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-scripts"
      - dependency-name: "reactstrap"
      - dependency-name: "jest"
      - dependency-name: "eslint"
