version: "2"
services:
  front-end:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - express-server
  express-server:
    build:
      context: ./express-server
    ports:
      - "5000:5000"
