version: "3.8"
services:
  # Frontend
  front-end:
    build:
      context: ./front-end
    depends_on:
      - express-server
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/src/.env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4318
      - DEMO_SERVER_ENDPOINT=http://localhost:3000
  # Backend
  express-server:
    build:
      context: ./express-server
    depends_on:
      - collector
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4318
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml'
    ports:
      - "4318:4318"