receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: http://localhost:55678/v1/traces
        cors_allowed_origins: http://localhost:3000

exporters:
  jaeger:
    endpoint: "http://localhost:14268/api/traces"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]