receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: localhost:4318
        cors:
          allowed_origins:
            - http://*
            - https://*
exporters:
  logging:
    loglevel: debug
processors:
  batch:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
