name: ci
on:
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: ./scripts/start.sh
      - run: |
          cd express-server
          npm install
          npm start &
      - run: |
          cd front-end
          npm install
          npm start &
      - run: |
          cd front-end
          npm test
      - run: ./scripts/check-traces.sh
      - run: ./scripts/stop.sh
